# -*- coding: utf-8 -*-
"""Regressão. Aprendizado Supervisionado  João Vitor Belasque Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiWIjvY2x0KJARUUAE5jQ25HCJDsQ-UM

SUPERVISED LEARNING: **REGRESSION**

This project aims to develop a Machine Learning algorithm to predict the average price of houses.

The data were extracted from the Kaggle website:

https://www.kaggle.com/schirmerchad/bostonhoustingmlnd
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Machine_Learning_com_Python/housing.csv',
                    sep=',', encoding='iso-8859-1')

df.head()

"""Predictor Attributes

RM: the average number of rooms per dwelling in the neighborhood.

LSTAT: the percentage of homeowners in the neighborhood considered to be of the “lower class” (working class).

PTRATIO: the pupil-to-teacher ratio in elementary and secondary schools in the neighborhood.

Target Variable

MEDV: median value of owner-occupied homes.
"""

df.shape

"""**DATA EXPLORATION AND PREPROCESSING**

Valores Missing (NAN)
"""

# RELAÇÃO DA QUANTIDADE
df.isnull().sum()

"""**Analysis of attribute types.**"""

# object: strings
# int64: inteiros
# float64: reais
# complex: complexos
df.dtypes

"""**Statistical Data.**"""

df.describe()

"""**Outlier analysis.**"""

import plotly.express as px

boxplot = px.box(df, y="RM")
boxplot.show()

boxplot = px.box(df, y="LSTAT")
boxplot.show()

boxplot = px.box(df, y="PTRATIO")
boxplot.show()

boxplot = px.box(df, y="MEDV")
boxplot.show()

"""## **CORRELAÇÃO LINEAR**"""

df.head(2)

"""**Atributos previsores**

RM: é o número médio de cômodos entre os imóveis no bairro.

LSTAT: é a porcentagem de proprietários no bairro considerados de "classe baixa" (proletariado).

PTRATIO: é a razão entre estudantes e professores nas escolas de ensino fundamental e médio no bairro.

**Variável alvo**

MEDV: valor médio das casas
"""

import matplotlib.pyplot as plt

plt.scatter(df.RM, df.MEDV)
plt.title('Correlação Linear')
plt.xlabel('Quantidade Média de Cômodos')
plt.ylabel('Valor Médio')
plt.grid(False)

plt.scatter(df.LSTAT, df.MEDV)
plt.title('Correlação Linear')
plt.xlabel('Quantidade Classe Baixa (%)')
plt.ylabel('Valor Médio')
plt.grid(True)

plt.scatter(df.PTRATIO, df.MEDV)
plt.title('Correlação Linear')
plt.xlabel('Estudantes/Professores')
plt.ylabel('Valor Médio')
plt.grid(False)

import seaborn as sns

sns.pairplot(df);

"""### Análise da Normalidade

Gráfico QQ-Plot
"""

import scipy.stats as stats

stats.probplot(df['MEDV'], dist="norm", plot=plt)
plt.title("Normal Q-Q plot")
plt.show()

import plotly.express as px

hist =  px.histogram (df,  x = "MEDV", nbins=60)
hist.update_layout(width=800,height=500,title_text='Média dos valores')
hist.show()

stats.probplot(df['RM'], dist="norm", plot=plt)
plt.title("Normal Q-Q plot")
plt.show()

hist =  px.histogram (df,  x = "RM", nbins=40)
hist.update_layout(width=800,height=500,title_text='Quantidade de cômodos')
hist.show()

stats.probplot(df['LSTAT'], dist="norm", plot=plt)
plt.title("Normal Q-Q plot")
plt.show()

hist =  px.histogram (df,  x = "LSTAT", nbins=60)
hist.update_layout(width=800,height=500,title_text='Quantidade de Classe Baixa (%)')
hist.show()

stats.probplot(df['PTRATIO'], dist="norm", plot=plt)
plt.title("Normal Q-Q plot")
plt.show()

hist =  px.histogram (df,  x = "PTRATIO", nbins=60)
hist.update_layout(width=800,height=500,title_text='Relação Estudantes/Professores')
hist.show()

"""Teste Shapiro-Wilk

Ho = distribuição normal : p > 0.05

Ha = distribuição != normal : p <= 0.05
"""

stats.shapiro(df.MEDV)

estatistica, p = stats.shapiro(df.MEDV)
print('Estatística do teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

estatistica, p = stats.shapiro(df.RM)
print('Estatística do teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

estatistica, p = stats.shapiro(df.LSTAT)
print('Estatística do teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

estatistica, p = stats.shapiro(df.PTRATIO)
print('Estatística do teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

"""Teste Lilliefors (Kolmogorov_Sminorv)

Ho = distribuição normal : p > 0.05

Ha = distribuição != normal : p <= 0.05
"""

import statsmodels
from statsmodels.stats.diagnostic import lilliefors

estatistica, p = statsmodels.stats.diagnostic.lilliefors(df.MEDV, dist = 'norm')
print('Estatística de teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

estatistica, p = statsmodels.stats.diagnostic.lilliefors(df.RM, dist = 'norm')
print('Estatística de teste: {}'.format(estatistica))
print('p-valor: {}'.format(p))

"""### Correlação Linear

Pearson (distribuição normal)

Spearman (distribuição não normal)

Kendall (distribuição não normal com quantidade pequena de amostras)

Ho = não há corrrelação linear: p > 0,05

Ha = existe correlação linear: p <= 0,05
"""

# Pearson
#coef,p = stats.pearsonr(df.MEDV, df.RM)
#print('Coeficiente de correlação: {}'.format(coef))
#print('p-valor: {}'.format(p))

# Spearman
coef,p = stats.spearmanr(df.MEDV, df.PTRATIO)
print('Coeficiente de correlação: {}'.format(coef))
print('p-valor: {}'.format(p))

# Kendall
#coef,p = stats.kendalltau(df.MEDV,df.RM)
#print('Coeficiente de correlação: {}'.format(coef))
#print('p-valor: {}'.format(p))

correlacoes = df.corr(method='spearman')
correlacoes

plt.figure()
sns.heatmap(correlacoes, annot=True);

"""## **REGRESSÃO LINEAR SIMPLES**

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

### Valor médio (MEDV) em função do número de cômodos (RM)
"""

df.head(2)

x1 = df.iloc[:,0:1].values
x1

y = df.iloc[:, 3].values
y

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x1, y, test_size = 0.3, random_state = 10)

x_treino.shape, y_treino.shape

x_teste.shape, y_teste.shape

from sklearn.linear_model import LinearRegression

reg_linear1 = LinearRegression()
reg_linear1.fit(x_treino, y_treino)

# Intercepto (coeficiente linear)
reg_linear1.intercept_

# Coeficiente Angular
reg_linear1.coef_

"""**Equação: Valor = -626510,27 + 173771,45.número_cômodos**"""

# Coeficiente de Determinação dados de treino
reg_linear1.score(x_treino, y_treino)

# Coeficiente de Determinação dados de teste
reg_linear1.score(x_teste, y_teste)

previsoes_treino = reg_linear1.predict(x_treino)
previsoes_treino

import matplotlib.pyplot as plt

plt.scatter(y=y_treino, x=x_treino, color='blue', s=10, alpha=0.9)
X_plot = np.linspace(3, 9)
plt.plot(X_plot, X_plot*reg_linear1.coef_ + reg_linear1.intercept_, color='r')
plt.title('Reta de regressão')
plt.ylabel('Valor Médio')
plt.xlabel('Quantidade Média de Cômodos')
plt.show()

previsoes_teste = reg_linear1.predict(x_teste)
previsoes_teste

y_teste

plt.scatter(y=y_teste, x=x_teste, color='blue', s=10, alpha=0.9)
X_plot = np.linspace(4, 9)
plt.plot(X_plot, X_plot*reg_linear1.coef_ + reg_linear1.intercept_, color='r')
plt.title('Reta de regressão')
plt.ylabel('Valor Médio')
plt.xlabel('Quantidade de Cômodos')
plt.show()

# Fazendo previsões para valores distintos
valor_casa = reg_linear1.predict([[4]])
valor_casa

"""**Métricas de Desempenho**"""

# Erro absoluto
abs(y_teste - previsoes_teste).mean()

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### Valor médio (MEDV) em função da classe social (LSTAT)"""

df.head(2)

x2 = df.iloc[:,1:2].values
x2

y = df.iloc[:, 3].values
y

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x2, y, test_size = 0.3, random_state = 10)

x_treino.shape, y_treino.shape

x_teste.shape, y_teste.shape

from sklearn.linear_model import LinearRegression
reg_linear2 = LinearRegression()
reg_linear2.fit(x_treino, y_treino)

# Intercepto (coeficiente linear)
reg_linear2.intercept_

# Coeficiente Angular
reg_linear2.coef_

"""**Equação: Valor = 681977,75 - 17263,75.LSTAT**"""

# Coeficiente de Determinação dados de treino
reg_linear2.score(x_treino, y_treino)

previsoes_treino = reg_linear2.predict(x_treino)
previsoes_treino

plt.scatter(y=y_treino, x=x_treino, color='blue', s=10, alpha=0.9)
X_plot = np.linspace(0, 40)
plt.plot(X_plot, X_plot*reg_linear2.coef_ + reg_linear2.intercept_, color='r')
plt.title('Reta de regressão')
plt.ylabel('Valor Médio')
plt.xlabel('Quantidade de Proprietários de Classe Média Baixa (%)')
plt.show()

previsoes_teste = reg_linear2.predict(x_teste)
previsoes_teste

y_teste

# Coeficiente de Determinação dados de teste
reg_linear2.score(x_teste, y_teste)

plt.scatter(y=y_teste, x=x_teste, color='blue', s=10, alpha=0.9)
X_plot = np.linspace(2, 35)
plt.plot(X_plot, X_plot*reg_linear2.coef_ + reg_linear2.intercept_, color='r')
plt.title('Reta de regressão')
plt.ylabel('Valor Médio')
plt.xlabel('Quantidade de Proprietários de Classe Média Baixa (%)')
plt.show()

# Fazendo previsões para valores distintos
valor_casa = reg_linear2.predict([[25]])
valor_casa

"""**Métricas de Desempenho**"""

# Erro absoluto
abs(y_teste - previsoes_teste).mean()

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Validação Cruzada**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from sklearn.linear_model import LinearRegression
modelo = LinearRegression()
resultado = cross_val_score(modelo, x2, y, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coef. determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""## **REGRESSÃO LINEAR MÚLTIPLA**"""

from sklearn.linear_model import LinearRegression

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values
dependente

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

multipla = LinearRegression()
multipla.fit(x_treino, y_treino)

multipla.intercept_

multipla.coef_

print("Equação: Valor = {:.2f} + ({:.2f})*RM + ({:.2f})*LSTAT + ({:.2f})*PTRATIO".format(multipla.intercept_, multipla.coef_[0], multipla.coef_[1], multipla.coef_[2]))

# Coeficiente de Determinação
multipla.score(x_treino, y_treino)

"""**TESTE**"""

previsoes = multipla.predict(x_teste)
previsoes

y_teste

# Coeficiente de Determinação
multipla.score(x_teste, y_teste)

# Fazendo previsões para valores distintos
valor_casa = multipla.predict([[6,20,12]])
valor_casa

"""**MÉTRICAS**"""

# Erro absoluto
abs(y_teste - previsoes).mean()

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes)

# Raiz do erro quadrático médio
np.sqrt(mean_squared_error(y_teste, previsoes))

"""### **Validação Cruzada**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from sklearn.linear_model import LinearRegression
modelo = LinearRegression()
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""**REGRESSÃO LINEAR SIMPLES:** R^2 = 0,57/0,60; RMSE = 99315,5; R^2 Validação Cruzada: 55,97%

**REGRESSÃO LINEAR MÚLTIPLA:** R^2 = 0,73/0,68; RMSE = 96087,3; R^2 Validação Cruzada: 69,25%

## **REGRESSÃO POLINOMIAL**

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html

Valor médio (MEDV) em função do número de cômodos (RM)
"""

df.head(2)

x1 = df.iloc[:,0:1].values
x1

y = df.iloc[:, 3].values
y

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x1, y, test_size = 0.3, random_state = 0)

x_treino.shape, y_treino.shape

x_teste.shape, y_teste.shape

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Pré Processamento
grau_polinomial =PolynomialFeatures(degree=2)

x_poly = grau_polinomial.fit_transform(x_treino)
x_poly

polinomial = LinearRegression()

polinomial.fit(x_poly, y_treino)

previsoes_treino = polinomial.predict(x_poly)

polinomial.coef_

polinomial.intercept_

"""**Equação:**

Valor = 1640107 - 568528.11*RM + 60092.59*RM^2
"""

numeros = np.linspace(3,9.84,342)
numeros

numeros.shape

valor = 1640107 -568528.11*numeros + 60092.59*numeros**2

import matplotlib.pyplot as plt

plt.scatter(x_treino, y_treino, c = "gray")
plt.xlabel("Quantidade Cômodos")
plt.ylabel("Valores das Casas")
plt.title("Previsão dos valores das casas: dados de treino")
plt.plot(numeros, valor);

# Fazendo previsões para valores distintos
comodos = 6
valor = 1640107 -568528.11*comodos + 60092.59*comodos**2
valor

# Coeficiente de Determinação dados de treino
polinomial.score(x_poly, y_treino)

"""**TESTE**"""

numeros2 = np.linspace(3,8.88,147)
numeros2

numeros2.shape

valor2 = 1640107 -568528.11*numeros2 + 60092.59*numeros2**2

import matplotlib.pyplot as plt

plt.scatter(x_teste, y_teste, c = "gray")
plt.xlabel("Quantidade Cômodos")
plt.ylabel("Valor Casas")
plt.title("Previsão dos valores das casas: dados de teste")
plt.plot(numeros2, valor2);

x_poly_teste = grau_polinomial.fit_transform(x_teste)
x_poly_teste

polinomial_teste = LinearRegression()

polinomial_teste.fit(x_poly_teste, y_teste)

# Coeficiente de Determinação dados de teste
polinomial.score(x_poly_teste, y_teste)

previsoes_teste = polinomial_teste.predict(x_poly_teste)

"""**MÉTRICAS**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""**RESULTADOS:**

**REGRESSÃO LINEAR SIMPLES:** R^2 = 0,57/0,60; RMSE = 99315,5; R^2 Validação Cruzada: 55,97%

**REGRESSÃO LINEAR MÚLTIPLA:** R^2 = 0,73/0,68; RMSE = 96087,3; R^2 Validação Cruzada: 69,25%

**REGRESSÃO POLINOMIAL:** R^2 = 0,59/0,54; RMSE = 114670,6.

## **REGRESSÃO POR VETORES DE SUPORTE**

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html
"""

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values
dependente

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

# kernel = rbf, linear, polinomial (poly)
from sklearn.svm import SVR
SVR = SVR(kernel='rbf')
SVR.fit(x_treino,y_treino)

SVR.score(x_treino, y_treino)

SVR.score(x_teste, y_teste)

"""**Padronização de escala**"""

from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
x_treino_scaler = x_scaler.fit_transform(x_treino)

x_treino_scaler

y_scaler = StandardScaler()
y_treino_scaler = y_scaler.fit_transform(y_treino.reshape(-1,1))

y_treino_scaler

x_teste_scaler = x_scaler.transform(x_teste)
x_teste_scaler

y_teste_scaler = y_scaler.transform(y_teste.reshape(-1,1))
y_teste_scaler

from sklearn.svm import SVR
SVR2 = SVR(kernel='rbf')
SVR2.fit(x_treino_scaler, y_treino_scaler.ravel())

# .ravel() é para retornar matriz 1D

SVR2.score(x_treino_scaler, y_treino_scaler)

"""**TESTE**"""

SVR2.score(x_teste_scaler, y_teste_scaler)

previsoes_teste = SVR2.predict(x_teste_scaler)
previsoes_teste

y_teste_scaler

"""**Revertendo a transformação**"""

y_teste_inverse = y_scaler.inverse_transform(y_teste_scaler)
previsoes_inverse = y_scaler.inverse_transform(previsoes_teste.reshape(-1, 1))

y_teste_inverse

previsoes_inverse

"""**MÉTRICAS**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste_inverse, previsoes_inverse)

# Erro quadrático médio
mean_squared_error(y_teste_inverse, previsoes_inverse)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste_inverse, previsoes_inverse))

"""### **Validação Cruzada**

**Padronização de escala**
"""

from sklearn.preprocessing import StandardScaler
x = StandardScaler()
independente_scaler = x.fit_transform(independente)

independente_scaler

y = StandardScaler()
dependente_scaler = y.fit_transform(dependente.reshape(-1,1))

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from sklearn.svm import SVR
modelo = SVR(kernel='rbf')
resultado = cross_val_score(modelo, independente_scaler, dependente_scaler.ravel(), cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação médio: %.2f%%" % (resultado.mean() * 100.0))

"""**RESULTADOS:**

**REGRESSÃO LINEAR SIMPLES:** R^2 = 0,57/0,60; RMSE = 99315,5; R^2 Validação Cruzada: 55,97%

**REGRESSÃO LINEAR MÚLTIPLA:** R^2 = 0,73/0,68; RMSE = 96087,3; R^2 Validação Cruzada: 69,25%

**REGRESSÃO POLINOMIAL:** R^2 = 0,59/0,54; RMSE = 114670,6.

**REGRESSÃO SVR:** R^2 = 0,87/0,81; RMSE = 73422,7. R^2 Validação Cruzada: 82,37%.

## **REGRESSÃO COM ÁRVORE DE DECISÃO**

https://scikit-learn.org/stable/modules/tree.html#regression
"""

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values
dependente

dependente.shape

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

y_treino.shape, y_teste.shape

from sklearn.tree import DecisionTreeRegressor
arvore = DecisionTreeRegressor(max_depth=5, random_state=10)
arvore.fit(x_treino, y_treino)

arvore.score(x_treino, y_treino)

"""**TESTE**"""

arvore.score(x_teste, y_teste)

previsoes_teste = arvore.predict(x_teste)
previsoes_teste

y_teste

"""**MÉTRICAS**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Cross Validation**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from sklearn.tree import DecisionTreeRegressor
modelo = DecisionTreeRegressor(max_depth=5, random_state=10)
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""RESULTS:

SIMPLE LINEAR REGRESSION: R² = 0.57 / 0.60; RMSE = 99,315.5; Cross-Validation R²: 55.97%

MULTIPLE LINEAR REGRESSION: R² = 0.73 / 0.68; RMSE = 96,087.3; Cross-Validation R²: 69.25%

POLYNOMIAL REGRESSION: R² = 0.59 / 0.54; RMSE = 114,670.6

SUPPORT VECTOR REGRESSION (SVR): R² = 0.87 / 0.81; RMSE = 73,422.7; Cross-Validation R²: 82.37%

DECISION TREE REGRESSION: R² = 0.91 / 0.83; RMSE = 71,114.5; Cross-Validation R²: 74.60%

## **REGRESSION WITH RANDOM FOREST**

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
"""

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values
dependente

dependente.shape

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

y_treino.shape, y_teste.shape

from sklearn.ensemble import RandomForestRegressor

random = RandomForestRegressor(n_estimators=60, criterion='squared_error', max_depth=5, random_state = 10)
random.fit(x_treino, y_treino)

random.score(x_treino, y_treino)

"""**TEST**"""

random.score(x_teste, y_teste)

previsoes_teste = random.predict(x_teste)
previsoes_teste

y_teste

"""**Metrics**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Erro quadrático médio
mean_squared_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Cross Validation**

"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from sklearn.ensemble import RandomForestRegressor
modelo = RandomForestRegressor(n_estimators=60, criterion='squared_error', max_depth=5, random_state = 10)
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""RESULTS:

Simple Linear Regression: R² = 0.57 / 0.60; RMSE = 99,315.5; Cross-Validation R² = 55.97%

Multiple Linear Regression: R² = 0.73 / 0.68; RMSE = 96,087.3; Cross-Validation R² = 69.25%

Polynomial Regression: R² = 0.59 / 0.54; RMSE = 114,670.6

Support Vector Regression (SVR): R² = 0.87 / 0.81; RMSE = 73,422.7; Cross-Validation R² = 82.37%

Decision Tree Regression: R² = 0.91 / 0.83; RMSE = 71,114.5; Cross-Validation R² = 74.60%

Random Forest Regression: R² = 0.92 / 0.85; RMSE = 66,729.3; Cross-Validation R² = 82.85%

If you whish, I can also:

Reformat this for a paper / thesis

Add a short interpretation of the results

Adapt it to IEEE / APA style

**XGBoost Regression**

https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor
"""

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values

dependente.shape

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

from xgboost import XGBRegressor

xgboost = XGBRegressor(n_estimators=180, max_depth=3, learning_rate=0.05, objective="reg:squarederror", random_state=10)
xgboost.fit(x_treino, y_treino)

xgboost.score(x_treino, y_treino)

"""**TEST**"""

xgboost.score(x_teste, y_teste)

previsoes_teste = xgboost.predict(x_teste)

# Fazendo previsões para valores distintos
valor_casa = xgboost.predict([[6,20,12]])
valor_casa

"""Metrics"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Cross-Validation**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from xgboost import XGBRegressor
modelo = XGBRegressor(n_estimators=180, max_depth=3, learning_rate=0.05, objective = "reg:squarederror")
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""RESULTS:

SIMPLE LINEAR REGRESSION: R² = 0.57 / 0.60; RMSE = 99,315.5; Cross-Validation R²: 55.97%

MULTIPLE LINEAR REGRESSION: R² = 0.73 / 0.68; RMSE = 96,087.3; Cross-Validation R²: 69.25%

POLYNOMIAL REGRESSION: R² = 0.59 / 0.54; RMSE = 114,670.6

SVR REGRESSION: R² = 0.87 / 0.81; RMSE = 73,422.7; Cross-Validation R²: 82.37%

DECISION TREE REGRESSION: R² = 0.91 / 0.83; RMSE = 71,114.5; Cross-Validation R²: 74.60%

RANDOM FOREST REGRESSION: R² = 0.92 / 0.85; RMSE = 66,729.3; Cross-Validation R²: 82.85%

XGBOOST REGRESSION: R² = 0.93 / 0.84; RMSE = 67,788.8; Cross-Validation R²: 83.22%

## **LightGBM Regression**

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html
"""

# Instalação do Algoritmo
!pip install lightgbm

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values

dependente.shape

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

import lightgbm as lgb

lgbm = lgb.LGBMRegressor(num_leaves=50, max_depth=3, learning_rate=0.1, n_estimators=50, random_state=10)
lgbm.fit(x_treino, y_treino)

lgbm.score(x_treino, y_treino)

"""**TEST**"""

lgbm.score(x_teste, y_teste)

previsoes_teste = lgbm.predict(x_teste)

# Fazendo previsões para valores distintos
valor_casa = lgbm.predict([[8,12,25]])
valor_casa

"""**METRICS**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Cross-Validation**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
import lightgbm as lgb
modelo = lgb.LGBMRegressor(num_leaves=50, max_depth=3, learning_rate=0.1, n_estimators=50)
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""RESULTS:

SIMPLE LINEAR REGRESSION: R² = 0.57 / 0.60; RMSE = 99,315.5; Cross-Validation R²: 55.97%

MULTIPLE LINEAR REGRESSION: R² = 0.73 / 0.68; RMSE = 96,087.3; Cross-Validation R²: 69.25%

POLYNOMIAL REGRESSION: R² = 0.59 / 0.54; RMSE = 114,670.6

SVR REGRESSION: R² = 0.87 / 0.81; RMSE = 73,422.7; Cross-Validation R²: 82.37%

DECISION TREE REGRESSION: R² = 0.91 / 0.83; RMSE = 71,114.5; Cross-Validation R²: 74.60%

RANDOM FOREST REGRESSION: R² = 0.92 / 0.85; RMSE = 66,729.3; Cross-Validation R²: 82.85%

XGBOOST REGRESSION: R² = 0.93 / 0.84; RMSE = 67,788.8; Cross-Validation R²: 83.22%

LIGHTGBM REGRESSION: R² = 0.88 / 0.82; RMSE = 71,906.4; Cross-Validation R²: 82.38%

## **CatBoost Regression**

*   Item da lista

*   Item da lista

*   Item da lista
*   Item da lista


*   Item da lista


*   Item da lista



*   Item da lista
*   Item da lista

https://catboost.ai/en/docs/concepts/python-reference_catboostregressor
"""

#Instalação
!pip install catboost

df.head(2)

independente = df.iloc[:, 0:3].values
independente

independente.shape

dependente = df.iloc[:, 3].values

dependente.shape

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

x_treino.shape, x_teste.shape

from catboost.core import CatBoostRegressor

catboost = CatBoostRegressor (iterations=100, learning_rate=0.08, depth = 5, random_state = 10)
catboost.fit(x_treino, y_treino)

catboost.score(x_treino, y_treino)

"""**TESTE**"""

catboost.score(x_teste, y_teste)

previsoes_teste = catboost.predict(x_teste)

# Fazendo previsões para valores distintos
valor_casa = catboost.predict([[5,18,20]])
valor_casa

"""

```
# Isto está formatado como código
```

**METRICS**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

"""### **Cross-Validation**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 15, shuffle=True, random_state = 5)

# Criando o modelo
from catboost.core import CatBoostRegressor
modelo = CatBoostRegressor (iterations=100, learning_rate=0.08, depth = 5, random_state = 10)
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

# Usamos a média e o desvio padrão
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

"""RESULTS:

SIMPLE LINEAR REGRESSION: R² = 0.57 / 0.60; RMSE = 99,315.5; Cross-Validation R²: 55.97%

MULTIPLE LINEAR REGRESSION: R² = 0.73 / 0.68; RMSE = 96,087.3; Cross-Validation R²: 69.25%

POLYNOMIAL REGRESSION: R² = 0.59 / 0.54; RMSE = 114,670.6

SVR REGRESSION: R² = 0.87 / 0.81; RMSE = 73,422.7; Cross-Validation R²: 82.37%

DECISION TREE REGRESSION: R² = 0.91 / 0.83; RMSE = 71,114.5; Cross-Validation R²: 74.60%

RANDOM FOREST REGRESSION: R² = 0.92 / 0.85; RMSE = 66,729.3; Cross-Validation R²: 82.85%

XGBOOST REGRESSION: R² = 0.93 / 0.84; RMSE = 67,788.8; Cross-Validation R²: 83.22%

LIGHTGBM REGRESSION: R² = 0.88 / 0.82; RMSE = 71,906.4; Cross-Validation R²: 82.38%

CATBOOST REGRESSION: R² = 0.90 / 0.84; RMSE = 69,053.3; Cross-Validation R²: 83.40%

**Saving data for deployment**
"""

independente = df.iloc[:, 0:3].values
independente

dependente = df.iloc[:, 3].values
dependente

np.savetxt('independente.csv', independente, delimiter=',')

np.savetxt('dependente.csv', dependente, delimiter=',')